(#9621) Return the puppet agent certname to the user
The behavior before this patch is that the certificate name of the newly
installed Puppet system is not returned to the end user of the face
action.

Dan brought this up in the code review as a concern.

This patch addresses the problem by running puppet agent --configprint
certname after installation has happened and capturing the standard
output of the remote command.  This is the certificate name
automatically generated by Puppet, the certificate name provided in the
answers file, or the certificate name provided by the
--puppetagent-certname command line option.

This patch also leaves the possibility for dynamically generated
certificate names on the remote system since we capture that generated
name post installation.

diff --git a/lib/puppet/cloudpack/scripts/puppet-enterprise-http.erb b/lib/puppet/cloudpack/scripts/puppet-enterprise-http.erb
--- a/lib/puppet/cloudpack/scripts/puppet-enterprise-http.erb
+++ b/lib/puppet/cloudpack/scripts/puppet-enterprise-http.erb
@@ -3,6 +3,17 @@ set -x
 set -e
 set -u
 
+# Figure out if we have wget or curl
+if which wget >/dev/null; then
+  http_get="wget --output-document=- --quiet"
+elif which curl >/dev/null; then
+  http_get="curl -o -"
+else
+  echo "Error: could not find wget or curl on the remote system."
+  echo "To install Puppet Enterprise using HTTP, wget or curl are required"
+  exit 1
+fi
+
 # The installer action determines a temporary directory internally
 # This is not a user defined option.  You may assume this will be
 # a unique string of characters.
@@ -35,17 +46,28 @@ echo "Downloading from: <%= options[:installer_payload] %>"
 # into.  This provides us with consistent pathing regardless of the PE
 # version.
 install_dir="puppet-enterprise"
-mkdir "${install_dir}"
+if [[ ! -e "${install_dir}" ]]; then
+  mkdir "${install_dir}"
+fi
 
 # We assume the payload is a tar.gz file because the option handler
 # enforces this.
 # To save disk space (I'm concerned about /tmp filling) decompress on the fly.
 echo "Uncompressing the payload ..."
-curl -o - '<%= options[:installer_payload] %>' | tar -xvzf - --strip-components 1 -C "${install_dir}"
+$http_get '<%= options[:installer_payload] %>' | \
+  tar -xvzf - --strip-components 1 -C "${install_dir}"
 # REVISIT (This assumes GNU tar with the --strip-components option)
 echo "Uncompressing the payload ... Done."
 
 # Finally, actually install Puppet Enterprise
 "${install_dir}"/puppet-enterprise-installer -a puppet.answers 2>&1 | tee install.log
+
+# And then kick off a puppet agent run
+/opt/puppet/bin/puppet agent --daemonize \
+  --onetime \
+  --ignorecache \
+  --no-usecacheonfailure \
+  --detailed-exitcodes \
+  --no-splay
 
 # vim:ft=sh
